#!/bin/zsh

FILEPATH=~/github/blog/docs/images/$1
# Two ways to assign a shell command to a variable
DIR=`dirname "$FILEPATH"`
FILE=$(basename "$FILEPATH")
if [ ! -d "$DIR" ]
then
    read ANS"?$DIR does not exists, do you want to create it?[y/n] "
    if [ $ANS = "y" ]
    then
        echo $DIR
        mkdir $DIR
    fi
fi

find ~/Documents -name "Screen\ Shot\ *" -print0 | xargs -0 -I {} mv {} ~/github/blog/docs/images/$1
