#!/bin/zsh
export TF_CPP_MIN_LOG_LEVEL=3
source activate drl
python run/eval.py "${@}"
# use the following command if the first argument is used to specify the source environment
# python run/eval.py "${@:2}"
